version: "3.8"

services:
  go:
    container_name: go
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "#kK36238708#"
      MYSQL_DATABASE: goapp
